In [146]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [147]:
df = pd.read_csv('BostonHousing.csv')

In [148]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93   0.0  0.573  6.030   NaN  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90    NaN  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99    NaN  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [149]:
df.info

<bound method DataFrame.info of         CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93   0.0  0.573  6.030   NaN  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.9

In [150]:
df.isnull().sum()

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [151]:
df.duplicated().sum()

np.int64(0)

In [152]:
df.fillna(0, inplace=True)  # Replace NaNs with 0


In [153]:
df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [154]:
df.describe()


CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.469112   10.768775   10.645889    0.067194    0.554695    6.284634   
std      8.574755   23.025124    7.039321    0.250605    0.115878    0.702617   
min      0.000000    0.000000    0.000000    0.000000    0.385000    3.561000   
25%      0.068907    0.000000    4.877500    0.000000    0.449000    5.885500   
50%      0.224635    0.000000    8.560000    0.000000    0.538000    6.208500   
75%      2.808720    0.000000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    65.810277    3.795043    9.549407  408.237154   18.455534  356.674032   
std     30.520606    2.105710    8.707259  168.537116    2.164946   91.294864   
min      0.000000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     40.425000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     74.450000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     93.575000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.212846   22.532806  
std      7.438324    9.197104  
min      0.000000    5.000000  
25%      6.590000   17.025000  
50%     10.925000   21.200000  
75%     16.570000   25.000000  
max     37.970000   50.000000

In [155]:
x = df[['CRIM','ZN',	'INDUS',	'CHAS',	'NOX',	'RM',	'AGE',	'DIS',	'RAD',	'TAX',	'PTRATIO',	'B',	'LSTAT']]
y = df[['MEDV']]

In [156]:
x

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93   0.0  0.573  6.030   0.0  2.5050    1  273   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   0.00  
..       ...     ...    ...  
501     21.0  391.99   0.00  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [157]:
y

MEDV
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

In [158]:
x_train , x_test, y_train , y_test = train_test_split(x,y,test_size= 0.3)

In [173]:
print('Training data shape :', x_train.shape)
print('Training label shape :', x_train.shape)
print('Testing data shape :', x_train.shape)
print('Testing label shape :', x_train.shape)

Training data shape : (354, 13)
Training label shape : (354, 13)
Testing data shape : (354, 13)
Testing label shape : (354, 13)


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [174]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train ,y_train)

LinearRegression()

In [168]:
lr.coef_

array([[-1.12407709,  0.94574432, -0.50301902,  0.54262369, -1.67952648,
         3.41164191, -0.19528326, -2.58371052,  2.42887315, -1.80222399,
        -1.82781654,  1.04637498, -2.32401872]])

In [169]:
lr.intercept_

array([22.50903955])

In [172]:
y_pred = lr.predict(x_test)
print(y_pred)

[[25.98045415]
 [19.97264756]
 [15.17179071]
 [18.90962424]
 [20.68564408]
 [17.00692405]
 [22.24668078]
 [23.57183085]
 [20.83975351]
 [21.48676629]
 [26.42982418]
 [30.31926801]
 [25.59723144]
 [23.53973082]
 [24.55541849]
 [25.29998922]
 [19.28507181]
 [ 9.3849621 ]
 [21.92858368]
 [21.22676393]
 [27.76793166]
 [15.52903322]
 [20.11942348]
 [18.49377883]
 [21.03575627]
 [20.49746776]
 [23.99465534]
 [32.0344226 ]
 [20.58098778]
 [ 7.28384619]
 [13.26376791]
 [16.65162765]
 [20.48683369]
 [24.36746388]
 [32.24863203]
 [22.06737644]
 [24.78431626]
 [29.50603991]
 [24.6904696 ]
 [21.0822679 ]
 [ 3.76510903]
 [24.13336936]
 [19.14349061]
 [27.06915385]
 [11.36405676]
 [25.08780698]
 [28.77593767]
 [16.75542038]
 [13.56922731]
 [21.00699848]
 [29.60626805]
 [28.92870095]
 [18.91901486]
 [27.13839703]
 [34.87196941]
 [20.98812495]
 [21.80859766]
 [35.817484  ]
 [16.58422768]
 [31.6046255 ]
 [15.62507583]
 [21.01006862]
 [22.41596533]
 [26.5626206 ]
 [17.25952814]
 [35.46231463]
 [16.71204

In [170]:
#Training Accuracy
print("Training accuracy is :")
lr.score(x_train, y_train)

Training accuracy is :


0.7395320859349686

In [171]:
#Testing Accuracy
print("Testing accuracy is : ")
lr.score(x_test, y_test)

Testing accuracy is : 


0.6871991907817732